all: hello_world math variable_types flow loops guessing_game arrays pointers

hello_world: hello_world.cpp
	g++ -Wall -pedantic -g -o hello_world hello_world.cpp

math: math.cpp
	g++ -Wall -pedantic -g -o math math.cpp

variable_types: variable_types.cpp
	g++ -Wall -pedantic -g -o variable_types variable_types.cpp

flow: flow.cpp
	g++ -Wall -pedantic -g -o flow flow.cpp

loops: loops.cpp
	g++ -Wall -pedantic -g -o loops loops.cpp

guessing_game: guessing_game.cpp
	g++ -Wall -pedantic -g -o guessing_game guessing_game.cpp

arrays: arrays.cpp
	g++ -Wall -pedantic -g -o arrays arrays.cpp

pointers: pointers.cpp
	g++ -Wall -pedantic -g -o pointers pointers.cpp

clean:
	rm -f *.o *.exe hello_world variable_types flow loops guessing_game arrays
